# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cei.pb import cei_internal_pb2 as cei__internal__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cei_internal_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LearnerInternalStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EstimateUtility = channel.unary_unary(
                '/cei.internal.v0_1.LearnerInternal/EstimateUtility',
                request_serializer=cei__internal__pb2.EstimateUtilityRequest.SerializeToString,
                response_deserializer=cei__internal__pb2.EstimateUtilityResponse.FromString,
                _registered_method=True)
        self.GetPolicySnapshot = channel.unary_unary(
                '/cei.internal.v0_1.LearnerInternal/GetPolicySnapshot',
                request_serializer=cei__internal__pb2.GetPolicySnapshotRequest.SerializeToString,
                response_deserializer=cei__internal__pb2.GetPolicySnapshotResponse.FromString,
                _registered_method=True)


class LearnerInternalServicer:
    """Missing associated documentation comment in .proto file."""

    def EstimateUtility(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPolicySnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LearnerInternalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EstimateUtility': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateUtility,
                    request_deserializer=cei__internal__pb2.EstimateUtilityRequest.FromString,
                    response_serializer=cei__internal__pb2.EstimateUtilityResponse.SerializeToString,
            ),
            'GetPolicySnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolicySnapshot,
                    request_deserializer=cei__internal__pb2.GetPolicySnapshotRequest.FromString,
                    response_serializer=cei__internal__pb2.GetPolicySnapshotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cei.internal.v0_1.LearnerInternal', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cei.internal.v0_1.LearnerInternal', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LearnerInternal:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EstimateUtility(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cei.internal.v0_1.LearnerInternal/EstimateUtility',
            cei__internal__pb2.EstimateUtilityRequest.SerializeToString,
            cei__internal__pb2.EstimateUtilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPolicySnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cei.internal.v0_1.LearnerInternal/GetPolicySnapshot',
            cei__internal__pb2.GetPolicySnapshotRequest.SerializeToString,
            cei__internal__pb2.GetPolicySnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HostServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunStep = channel.unary_unary(
                '/cei.internal.v0_1.HostService/RunStep',
                request_serializer=cei__internal__pb2.RunStepRequest.SerializeToString,
                response_deserializer=cei__internal__pb2.RunStepResponse.FromString,
                _registered_method=True)


class HostServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RunStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HostServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunStep': grpc.unary_unary_rpc_method_handler(
                    servicer.RunStep,
                    request_deserializer=cei__internal__pb2.RunStepRequest.FromString,
                    response_serializer=cei__internal__pb2.RunStepResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cei.internal.v0_1.HostService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cei.internal.v0_1.HostService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HostService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cei.internal.v0_1.HostService/RunStep',
            cei__internal__pb2.RunStepRequest.SerializeToString,
            cei__internal__pb2.RunStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AdapterHubStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpsertAdapter = channel.unary_unary(
                '/cei.internal.v0_1.AdapterHub/UpsertAdapter',
                request_serializer=cei__internal__pb2.UpsertAdapterRequest.SerializeToString,
                response_deserializer=cei__internal__pb2.UpsertAdapterResponse.FromString,
                _registered_method=True)
        self.GetAdapter = channel.unary_unary(
                '/cei.internal.v0_1.AdapterHub/GetAdapter',
                request_serializer=cei__internal__pb2.GetAdapterRequest.SerializeToString,
                response_deserializer=cei__internal__pb2.GetAdapterResponse.FromString,
                _registered_method=True)


class AdapterHubServicer:
    """Missing associated documentation comment in .proto file."""

    def UpsertAdapter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAdapter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdapterHubServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpsertAdapter': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertAdapter,
                    request_deserializer=cei__internal__pb2.UpsertAdapterRequest.FromString,
                    response_serializer=cei__internal__pb2.UpsertAdapterResponse.SerializeToString,
            ),
            'GetAdapter': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAdapter,
                    request_deserializer=cei__internal__pb2.GetAdapterRequest.FromString,
                    response_serializer=cei__internal__pb2.GetAdapterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cei.internal.v0_1.AdapterHub', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cei.internal.v0_1.AdapterHub', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdapterHub:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpsertAdapter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cei.internal.v0_1.AdapterHub/UpsertAdapter',
            cei__internal__pb2.UpsertAdapterRequest.SerializeToString,
            cei__internal__pb2.UpsertAdapterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAdapter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cei.internal.v0_1.AdapterHub/GetAdapter',
            cei__internal__pb2.GetAdapterRequest.SerializeToString,
            cei__internal__pb2.GetAdapterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
