# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cei.pb import cei_pb2 as cei__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cei_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExpertRegistryStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterExpert = channel.unary_unary(
                '/cei.v0_1.ExpertRegistry/RegisterExpert',
                request_serializer=cei__pb2.RegisterExpertRequest.SerializeToString,
                response_deserializer=cei__pb2.RegisterExpertResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/cei.v0_1.ExpertRegistry/Heartbeat',
                request_serializer=cei__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=cei__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.Deregister = channel.unary_unary(
                '/cei.v0_1.ExpertRegistry/Deregister',
                request_serializer=cei__pb2.DeregisterRequest.SerializeToString,
                response_deserializer=cei__pb2.DeregisterResponse.FromString,
                _registered_method=True)
        self.DescribeExperts = channel.unary_unary(
                '/cei.v0_1.ExpertRegistry/DescribeExperts',
                request_serializer=cei__pb2.DescribeExpertsRequest.SerializeToString,
                response_deserializer=cei__pb2.DescribeExpertsResponse.FromString,
                _registered_method=True)


class ExpertRegistryServicer:
    """Missing associated documentation comment in .proto file."""

    def RegisterExpert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deregister(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeExperts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExpertRegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterExpert': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterExpert,
                    request_deserializer=cei__pb2.RegisterExpertRequest.FromString,
                    response_serializer=cei__pb2.RegisterExpertResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=cei__pb2.HeartbeatRequest.FromString,
                    response_serializer=cei__pb2.HeartbeatResponse.SerializeToString,
            ),
            'Deregister': grpc.unary_unary_rpc_method_handler(
                    servicer.Deregister,
                    request_deserializer=cei__pb2.DeregisterRequest.FromString,
                    response_serializer=cei__pb2.DeregisterResponse.SerializeToString,
            ),
            'DescribeExperts': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeExperts,
                    request_deserializer=cei__pb2.DescribeExpertsRequest.FromString,
                    response_serializer=cei__pb2.DescribeExpertsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cei.v0_1.ExpertRegistry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cei.v0_1.ExpertRegistry', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExpertRegistry:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterExpert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cei.v0_1.ExpertRegistry/RegisterExpert',
            cei__pb2.RegisterExpertRequest.SerializeToString,
            cei__pb2.RegisterExpertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cei.v0_1.ExpertRegistry/Heartbeat',
            cei__pb2.HeartbeatRequest.SerializeToString,
            cei__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Deregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cei.v0_1.ExpertRegistry/Deregister',
            cei__pb2.DeregisterRequest.SerializeToString,
            cei__pb2.DeregisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DescribeExperts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cei.v0_1.ExpertRegistry/DescribeExperts',
            cei__pb2.DescribeExpertsRequest.SerializeToString,
            cei__pb2.DescribeExpertsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CombinationRouterStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProposeCombinations = channel.unary_unary(
                '/cei.v0_1.CombinationRouter/ProposeCombinations',
                request_serializer=cei__pb2.ProposeCombinationsRequest.SerializeToString,
                response_deserializer=cei__pb2.ProposeCombinationsResponse.FromString,
                _registered_method=True)


class CombinationRouterServicer:
    """Missing associated documentation comment in .proto file."""

    def ProposeCombinations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CombinationRouterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProposeCombinations': grpc.unary_unary_rpc_method_handler(
                    servicer.ProposeCombinations,
                    request_deserializer=cei__pb2.ProposeCombinationsRequest.FromString,
                    response_serializer=cei__pb2.ProposeCombinationsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cei.v0_1.CombinationRouter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cei.v0_1.CombinationRouter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CombinationRouter:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProposeCombinations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cei.v0_1.CombinationRouter/ProposeCombinations',
            cei__pb2.ProposeCombinationsRequest.SerializeToString,
            cei__pb2.ProposeCombinationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ExpertNodeStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LeaseCapacity = channel.unary_unary(
                '/cei.v0_1.ExpertNode/LeaseCapacity',
                request_serializer=cei__pb2.LeaseCapacityRequest.SerializeToString,
                response_deserializer=cei__pb2.LeaseCapacityResponse.FromString,
                _registered_method=True)
        self.ReleaseCapacity = channel.unary_unary(
                '/cei.v0_1.ExpertNode/ReleaseCapacity',
                request_serializer=cei__pb2.ReleaseCapacityRequest.SerializeToString,
                response_deserializer=cei__pb2.ReleaseCapacityResponse.FromString,
                _registered_method=True)
        self.ForwardExpert = channel.unary_unary(
                '/cei.v0_1.ExpertNode/ForwardExpert',
                request_serializer=cei__pb2.ForwardExpertRequest.SerializeToString,
                response_deserializer=cei__pb2.ForwardExpertResponse.FromString,
                _registered_method=True)
        self.ExportWeights = channel.unary_unary(
                '/cei.v0_1.ExpertNode/ExportWeights',
                request_serializer=cei__pb2.ExportWeightsRequest.SerializeToString,
                response_deserializer=cei__pb2.ExportWeightsResponse.FromString,
                _registered_method=True)


class ExpertNodeServicer:
    """Missing associated documentation comment in .proto file."""

    def LeaseCapacity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseCapacity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForwardExpert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportWeights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExpertNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LeaseCapacity': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaseCapacity,
                    request_deserializer=cei__pb2.LeaseCapacityRequest.FromString,
                    response_serializer=cei__pb2.LeaseCapacityResponse.SerializeToString,
            ),
            'ReleaseCapacity': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseCapacity,
                    request_deserializer=cei__pb2.ReleaseCapacityRequest.FromString,
                    response_serializer=cei__pb2.ReleaseCapacityResponse.SerializeToString,
            ),
            'ForwardExpert': grpc.unary_unary_rpc_method_handler(
                    servicer.ForwardExpert,
                    request_deserializer=cei__pb2.ForwardExpertRequest.FromString,
                    response_serializer=cei__pb2.ForwardExpertResponse.SerializeToString,
            ),
            'ExportWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportWeights,
                    request_deserializer=cei__pb2.ExportWeightsRequest.FromString,
                    response_serializer=cei__pb2.ExportWeightsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cei.v0_1.ExpertNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cei.v0_1.ExpertNode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExpertNode:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LeaseCapacity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cei.v0_1.ExpertNode/LeaseCapacity',
            cei__pb2.LeaseCapacityRequest.SerializeToString,
            cei__pb2.LeaseCapacityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseCapacity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cei.v0_1.ExpertNode/ReleaseCapacity',
            cei__pb2.ReleaseCapacityRequest.SerializeToString,
            cei__pb2.ReleaseCapacityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForwardExpert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cei.v0_1.ExpertNode/ForwardExpert',
            cei__pb2.ForwardExpertRequest.SerializeToString,
            cei__pb2.ForwardExpertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cei.v0_1.ExpertNode/ExportWeights',
            cei__pb2.ExportWeightsRequest.SerializeToString,
            cei__pb2.ExportWeightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CombinationLearnerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportOutcome = channel.unary_unary(
                '/cei.v0_1.CombinationLearner/ReportOutcome',
                request_serializer=cei__pb2.ReportOutcomeRequest.SerializeToString,
                response_deserializer=cei__pb2.ReportOutcomeResponse.FromString,
                _registered_method=True)


class CombinationLearnerServicer:
    """Missing associated documentation comment in .proto file."""

    def ReportOutcome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CombinationLearnerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportOutcome': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportOutcome,
                    request_deserializer=cei__pb2.ReportOutcomeRequest.FromString,
                    response_serializer=cei__pb2.ReportOutcomeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cei.v0_1.CombinationLearner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cei.v0_1.CombinationLearner', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CombinationLearner:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReportOutcome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cei.v0_1.CombinationLearner/ReportOutcome',
            cei__pb2.ReportOutcomeRequest.SerializeToString,
            cei__pb2.ReportOutcomeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
